### ISSUE TITLE
Add ability to use fancy script resource

### ISSUE THREAD

**Issue by patcon** [irvingpop/fancy_execute#3]
The execute resource can't choose the shell environment, which can have downsides. For example, `source` command is available in default shell on centos, but not ubuntu.

**Comment by irvingpop** [comment]
hey Patrick, could you give me some examples of how this doesn't work for you?

Also, did you know that a slightly more complete implementation of this landed into core Chef and shipped in 12.6.0?  https://github.com/chef/chef/pull/4040

**Comment by patcon** [comment]
Hm. You know, I think I got turned around. I was testing in a branch that didn't have fancy_execute as a dep :)

My bad. And thanks for the pointer. That'll come in handy for test-kitchen on travis
